### PR TITLE
Explore V1

### PR DESCRIPTION
**Pull request by LeshemNoa**

### CODE REVIEW

**Comment by hagaishapira** [comment]
Why did you have to choose an existing branch name ? 😢

**Comment by hagaishapira** [comment]
image
issues on my screen

**Comment by hagaishapira** [comment]
BTW why am I not seeing popular?

**Comment by hagaishapira** [comment]
image
Another issue, search box, explore title and leftmost recipe card must align, as well as right edge and rightmost recipe card.

**Comment by LeshemNoa** [comment]
@hagaishapira I fixed everything you mentioned but popular & personal. I want to see it in production because at the moment I am not getting these.

**Comment by LeshemNoa** [comment]
Ok @hagaishapira what you're going to see now when you launch the client is a loading screen that I created, it's supposed to go away once explore is populated (atm just explore as I never got to experience popular & personal, never got them from the server in the first place). Then I started working on replacing the gifs when my computer crashed, and after reboot I started getting these 404s consistently.

**Comment by hagaishapira** [comment]
@LeshemNoa can you rebase ?

**Pull request merged**
